begin;

create type public.user_role as enum ('admin', 'employee', 'liaison_officer', 'technical_support');
create type public.request_status as enum ('new', 'under_review', 'waiting_customer', 'in_progress', 'completed', 'cancelled');
create type public.request_priority as enum ('low', 'normal', 'high', 'urgent');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'أبو مشاري',
  role public.user_role not null default 'employee',
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.news_items (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 5 and 240),
  category text not null default 'عام',
  source_name text not null,
  source_url text not null check (source_url ~ '^https?://'),
  published_at timestamptz,
  priority integer not null default 0,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.requests (
  id uuid primary key default gen_random_uuid(),
  tracking_code text not null unique,
  customer_name text not null,
  phone text not null,
  city text not null,
  service_code text not null,
  details text not null,
  source text not null default 'website',
  status public.request_status not null default 'new',
  priority public.request_priority not null default 'normal',
  assigned_to uuid references public.profiles(id) on delete set null,
  internal_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.requests(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  note text,
  old_status public.request_status,
  new_status public.request_status,
  created_at timestamptz not null default now()
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index requests_created_at_idx on public.requests (created_at desc);
create index requests_status_idx on public.requests (status, created_at desc);
create index requests_assigned_to_idx on public.requests (assigned_to, status);
create index news_items_public_idx on public.news_items (is_active, priority desc, published_at desc);
create index request_events_request_idx on public.request_events (request_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger news_items_set_updated_at before update on public.news_items
for each row execute function public.set_updated_at();
create trigger requests_set_updated_at before update on public.requests
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), 'أبو مشاري'));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() and is_active = true
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and is_active = true
      and role in ('admin', 'employee', 'liaison_officer', 'technical_support')
  )
$$;

alter table public.profiles enable row level security;
alter table public.news_items enable row level security;
alter table public.requests enable row level security;
alter table public.request_events enable row level security;
alter table public.site_settings enable row level security;

create policy profiles_self_or_admin_select
on public.profiles for select to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

create policy profiles_admin_update
on public.profiles for update to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy news_public_select
on public.news_items for select to anon, authenticated
using (is_active = true or public.is_staff());

create policy news_staff_insert
on public.news_items for insert to authenticated
with check (public.is_staff());

create policy news_staff_update
on public.news_items for update to authenticated
using (public.is_staff()) with check (public.is_staff());

create policy news_admin_delete
on public.news_items for delete to authenticated
using (public.current_user_role() = 'admin');

create policy requests_public_insert
on public.requests for insert to anon, authenticated
with check (
  source in ('website', 'whatsapp', 'manual')
  and char_length(customer_name) between 2 and 120
  and char_length(phone) between 8 and 30
  and char_length(details) between 3 and 1500
);

create policy requests_staff_select
on public.requests for select to authenticated
using (public.is_staff());

create policy requests_staff_update
on public.requests for update to authenticated
using (public.is_staff()) with check (public.is_staff());

create policy request_events_staff_all
on public.request_events for all to authenticated
using (public.is_staff()) with check (public.is_staff());

create policy settings_public_select
on public.site_settings for select to anon, authenticated
using (is_public = true or public.is_staff());

create policy settings_admin_all
on public.site_settings for all to authenticated
using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');

grant usage on schema public to anon, authenticated;
grant select on public.news_items to anon, authenticated;
grant insert on public.requests to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.news_items, public.requests, public.request_events, public.site_settings to authenticated;
grant usage, select on sequence public.request_events_id_seq to authenticated;

insert into public.site_settings (key, value, is_public)
values
  ('contact', jsonb_build_object('whatsapp', '966590097275', 'tiktok', 'https://www.tiktok.com/@mror_angazk'), true),
  ('seasonal_banner', jsonb_build_object('enabled', true, 'season', 'اليوم الوطني السعودي 96', 'headline', 'كل معاملة نخدمها.. هي خدمة لوطن أعظم'), true)
on conflict (key) do nothing;

commit;
